In [338]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [339]:
dt = pd.read_csv('covid_worldwide.csv')
dt.head()

,Serial Number,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Total Test,Population
0,1,USA,"104,196,861","1,132,935","101,322,779","1,741,147","1,159,832,679","334,805,269"
1,2,India,"44,682,784","530,740","44,150,289","1,755","915,265,788","1,406,631,776"
2,3,France,"39,524,311","164,233","39,264,546","95,532","271,490,188","65,584,518"
3,4,Germany,"37,779,833","165,711","37,398,100","216,022","122,332,384","83,883,596"
4,5,Brazil,"36,824,580","697,074","35,919,372","208,134","63,776,166","215,353,593"

In [340]:
dt.dtypes

Serial Number       int64
Country            object
Total Cases        object
Total Deaths       object
Total Recovered    object
Active Cases       object
Total Test         object
Population         object
dtype: object

In [341]:
dt['Total Cases'] = pd.to_numeric(dt['Total Cases'], errors='coerce', downcast='float')
dt['Total Deaths'] = pd.to_numeric(dt['Total Deaths'], errors='coerce', downcast='float')
dt['Total Recovered'] = pd.to_numeric(dt['Total Recovered'], errors='coerce', downcast='float')
dt['Active Cases'] = pd.to_numeric(dt['Active Cases'], errors='coerce', downcast='float')
dt['Total Test'] = pd.to_numeric(dt['Total Test'], errors='coerce', downcast='float')
dt['Population'] = pd.to_numeric(dt['Population'], errors='coerce', downcast='float')

In [342]:
dt.dtypes

Serial Number        int64
Country             object
Total Cases        float32
Total Deaths       float32
Total Recovered    float32
Active Cases       float32
Total Test         float32
Population         float32
dtype: object

In [343]:
dt

,Serial Number,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Total Test,Population
0,1,USA,NaN,NaN,NaN,NaN,NaN,NaN
1,2,India,NaN,NaN,NaN,NaN,NaN,NaN
2,3,France,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Germany,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Brazil,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
226,227,Diamond Princess,712.0,13.0,699.0,0.0,NaN,NaN
227,228,Vatican City,29.0,NaN,29.0,0.0,NaN,799.0
228,229,Western Sahara,10.0,1.0,9.0,0.0,NaN,NaN
229,230,MS Zaandam,9.0,2.0,7.0,0.0,NaN,NaN
230,231,Tokelau,5.0,NaN,NaN,5.0,NaN,NaN

In [344]:
dt.isnull().sum()

Serial Number        0
Country              0
Total Cases        225
Total Deaths       139
Total Recovered    224
Active Cases       129
Total Test         231
Population         230
dtype: int64

In [345]:
x = dt.iloc[: , 1:5].values
y = dt.iloc[:, -3:-1].values
z = dt.iloc[:, -1].values

In [346]:
print(x)

[['USA' nan nan nan]
 ['India' nan nan nan]
 ['France' nan nan nan]
 ['Germany' nan nan nan]
 ['Brazil' nan nan nan]
 ['Japan' nan nan nan]
 ['S. Korea' nan nan nan]
 ['Italy' nan nan nan]
 ['UK' nan nan nan]
 ['Russia' nan nan nan]
 ['Turkey' nan nan nan]
 ['Spain' nan nan nan]
 ['Vietnam' nan nan nan]
 ['Australia' nan nan nan]
 ['Argentina' nan nan nan]
 ['Taiwan' nan nan nan]
 ['Netherlands' nan nan nan]
 ['Iran' nan nan nan]
 ['Mexico' nan nan nan]
 ['Indonesia' nan nan nan]
 ['Poland' nan nan nan]
 ['Colombia' nan nan nan]
 ['Austria' nan nan nan]
 ['Greece' nan nan nan]
 ['Portugal' nan nan nan]
 ['Ukraine' nan nan nan]
 ['Chile' nan nan nan]
 ['Malaysia' nan nan nan]
 ['Israel' nan nan nan]
 ['DPRK' nan 74.0 nan]
 ['Thailand' nan nan nan]
 ['Belgium' nan nan nan]
 ['Czechia' nan nan nan]
 ['Canada' nan nan nan]
 ['Peru' nan nan nan]
 ['Switzerland' nan nan nan]
 ['Philippines' nan nan nan]
 ['South Africa' nan nan nan]
 ['Romania' nan nan nan]
 ['Denmark' nan nan nan]
 ['Hong Kong' nan nan nan]
 ['Sweden' nan nan nan]
 ['Serbia' nan nan nan]
 ['Iraq' nan nan nan]
 ['Singapore' nan nan nan]
 ['Hungary' nan nan nan]
 ['New Zealand' nan nan nan]
 ['Bangladesh' nan nan nan]
 ['Slovakia' nan nan nan]
 ['Georgia' nan nan nan]
 ['Jordan' nan nan nan]
 ['Ireland' nan nan nan]
 ['Pakistan' nan nan nan]
 ['Norway' nan nan nan]
 ['Finland' nan nan nan]
 ['Kazakhstan' nan nan nan]
 ['Slovenia' nan nan nan]
 ['Lithuania' nan nan nan]
 ['Bulgaria' nan nan nan]
 ['Morocco' nan nan nan]
 ['Croatia' nan nan nan]
 ['Lebanon' nan nan nan]
 ['Guatemala' nan nan nan]
 ['Bolivia' nan nan nan]
 ['Costa Rica' nan nan nan]
 ['Tunisia' nan nan nan]
 ['Cuba' nan nan nan]
 ['Ecuador' nan nan nan]
 ['UAE' nan nan nan]
 ['Uruguay' nan nan nan]
 ['Panama' nan nan nan]
 ['Mongolia' nan nan nan]
 ['Nepal' nan nan nan]
 ['Belarus' nan nan nan]
 ['Latvia' nan nan nan]
 ['Saudi Arabia' nan nan nan]
 ['Azerbaijan' nan nan nan]
 ['Paraguay' nan nan nan]
 ['Bahrain' nan nan nan]
 ['Sri Lanka' nan nan nan]
 ['Kuwait' nan nan nan]
 ['Dominican Republic' nan nan nan]
 ['Cyprus' nan nan nan]
 ['Myanmar' nan nan nan]
 ['Palestine' nan nan nan]
 ['Estonia' nan nan nan]
 ['Moldova' nan nan nan]
 ['Venezuela' nan nan nan]
 ['Egypt' nan nan nan]
 ['Libya' nan nan nan]
 ['China' nan nan nan]
 ['Ethiopia' nan nan nan]
 ['Qatar' nan 686.0 nan]
 ['Réunion' nan 919.0 nan]
 ['Honduras' nan nan nan]
 ['Armenia' nan nan nan]
 ['Bosnia and Herzegovina' nan nan nan]
 ['Oman' nan nan nan]
 ['North Macedonia' nan nan nan]
 ['Kenya' nan nan nan]
 ['Zambia' nan nan nan]
 ['Albania' nan nan nan]
 ['Botswana' nan nan nan]
 ['Luxembourg' nan nan nan]
 ['Montenegro' nan nan nan]
 ['Brunei' nan 225.0 nan]
 ['Algeria' nan nan nan]
 ['Nigeria' nan nan nan]
 ['Zimbabwe' nan nan nan]
 ['Uzbekistan' nan nan nan]
 ['Mozambique' nan nan nan]
 ['Martinique' nan nan nan]
 ['Laos' nan 758.0 nan]
 ['Iceland' nan 229.0 nan]
 ['Afghanistan' nan nan nan]
 ['Kyrgyzstan' nan nan nan]
 ['El Salvador' nan nan nan]
 ['Guadeloupe' nan nan nan]
 ['Trinidad and Tobago' nan nan nan]
 ['Maldives' nan 311.0 nan]
 ['Ghana' nan nan nan]
 ['Namibia' nan nan nan]
 ['Uganda' nan nan nan]
 ['Jamaica' nan nan nan]
 ['Cambodia' nan nan nan]
 ['Rwanda' nan nan nan]
 ['Cameroon' nan nan nan]
 ['Malta' nan 824.0 nan]
 ['Barbados' nan 571.0 nan]
 ['Angola' nan nan nan]
 ['Channel Islands' nan 223.0 nan]
 ['French Guiana' nan 420.0 nan]
 ['DRC' nan nan nan]
 ['Senegal' nan nan nan]
 ['Malawi' nan nan nan]
 ['Ivory Coast' nan 833.0 nan]
 ['Suriname' nan nan nan]
 ['New Caledonia' nan 314.0 nan]
 ['French Polynesia' nan 649.0 nan]
 ['Eswatini' nan nan nan]
 ['Guyana' nan nan nan]
 ['Belize' nan 688.0 nan]
 ['Fiji' nan 883.0 nan]
 ['Madagascar' nan nan nan]
 ['Sudan' nan nan nan]
 ['Mauritania' nan 997.0 nan]
 ['Cabo Verde' nan 413.0 nan]
 ['Bhutan' nan 21.0 nan]
 ['Syria' nan nan nan]
 ['Burundi' nan 38.0 nan]
 ['Seychelles' nan 172.0 nan]
 ['Gabon' nan 306.0 nan]
 ['Andorra' nan 165.0 nan]
 ['Papua New Guinea' nan 670.0 nan]
 ['Curaçao' nan 295.0 nan]
 ['Aruba' nan 236.0 nan]
 ['Tanzania' nan 846.0 nan]
 ['Mayotte' nan 188.0 nan]
 ['Mauritius' nan nan nan]
 ['Togo' nan 290.0 nan]
 ['Guinea' nan 467.0 nan]
 ['Isle of Man' nan 116.0 nan]
 ['Bahamas' nan 833.0 nan]
 ['Lesotho' nan 723.0 nan]
 ['Faeroe Islands' nan 28.0 nan]
 ['Haiti' nan 860.0 nan]
 ['Mali' nan 743.0 nan]
 ['Cayman Islands' nan 37.0 nan]
 ['Saint Lucia' nan 409.0 nan]
 ['Benin' nan 163.0 nan]
 ['Somalia' nan nan nan]
 ['Congo' nan 386.0 nan]
 ['Solomon Islands' nan 153.0 nan]
 ['San Marino' nan 122.0 nan]
 ['Timor-Leste' nan 138.0 nan]
 ['Micronesia' nan 58.0 nan]
 ['Burkina Faso' nan 396.0 nan]
 ['Liechtenstein' nan 89.0 nan]
 ['Gibraltar' nan 111.0 nan]
 ['Grenada' nan 238.0 nan]
 ['Bermuda' nan 157.0 nan]
 ['Nicaragua' nan 225.0 nan]
 ['South Sudan' nan 138.0 nan]
 ['Tajikistan' nan 125.0 nan]
 ['Equatorial Guinea' nan 183.0 nan]
 ['Tonga' nan 13.0 nan]
 ['Samoa' nan 29.0 nan]
 ['Monaco' nan 65.0 nan]
 ['Dominica' nan 74.0 nan]
 ['Djibouti' nan 189.0 nan]
 ['Marshall Islands' nan 17.0 nan]
 ['CAR' nan 113.0 nan]
 ['Gambia' nan 372.0 nan]
 ['Saint Martin' nan 63.0 nan]
 ['Vanuatu' nan 14.0 nan]
 ['Greenland' nan 21.0 nan]
 ['Yemen' nan nan nan]
 ['Caribbean Netherlands' nan 38.0 nan]
 ['Sint Maarten' nan 89.0 nan]
 ['Eritrea' nan 103.0 nan]
 ['Niger' nan 312.0 nan]
 ['St. Vincent Grenadines' nan 123.0 nan]
 ['Antigua and Barbuda' nan 146.0 nan]
 ['Comoros' nan 161.0 nan]
 ['Guinea-Bissau' nan 176.0 nan]
 ['Liberia' nan 294.0 nan]
 ['Sierra Leone' nan 126.0 nan]
 ['Chad' nan 194.0 nan]
 ['British Virgin Islands' nan 64.0 nan]
 ['Cook Islands' nan 2.0 nan]
 ['Saint Kitts and Nevis' nan 46.0 nan]
 ['Turks and Caicos' nan 38.0 nan]
 ['Sao Tome and Principe' nan 77.0 nan]
 ['Palau' nan 9.0 nan]
 ['St. Barth' nan 6.0 nan]
 ['Kiribati' nan 18.0 nan]
 ['Nauru' nan 1.0 nan]
 ['Anguilla' nan 12.0 nan]
 ['Macao' nan 120.0 nan]
 ['Saint Pierre Miquelon' nan 2.0 nan]
 ['Wallis and Futuna' nan 7.0 438.0]
 ['Tuvalu' nan nan nan]
 ['Saint Helena' nan nan 2.0]
 ['Falkland Islands' nan nan nan]
 ['Montserrat' nan 8.0 nan]
 ['Niue' 747.0 nan 746.0]
 ['Diamond Princess' 712.0 13.0 699.0]
 ['Vatican City' 29.0 nan 29.0]
 ['Western Sahara' 10.0 1.0 9.0]
 ['MS Zaandam' 9.0 2.0 7.0]
 ['Tokelau' 5.0 nan nan]]

In [347]:
print(y)

[[ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [  0.  nan]
 [483.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [673.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [638.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [909.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ 63.  nan]
 [535.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [109.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [899.  nan]
 [ 34.  nan]
 [ 18.  nan]
 [ nan  nan]
 [307.  nan]
 [ nan  nan]
 [205.  nan]
 [ nan  nan]
 [509.  nan]
 [  3.  nan]
 [ 51.  nan]
 [ nan  nan]
 [ nan  nan]
 [ 31.  nan]
 [159.  nan]
 [ nan  nan]
 [ nan  nan]
 [739.  nan]
 [ nan  nan]
 [  4.  nan]
 [ nan  nan]
 [ nan  nan]
 [263.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [167.  nan]
 [ 82.  nan]
 [ nan  nan]
 [ nan  nan]
 [493.  nan]
 [ nan  nan]
 [348.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [956.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [318.  nan]
 [ nan  nan]
 [ 14.  nan]
 [201.  nan]
 [ nan  nan]
 [ nan  nan]
 [ 13.  nan]
 [ 63.  nan]
 [ nan  nan]
 [615.  nan]
 [ 16.  nan]
 [ 37.  nan]
 [115.  nan]
 [ nan  nan]
 [ nan  nan]
 [  2.  nan]
 [504.  nan]
 [ 11.  nan]
 [ nan  nan]
 [  5.  nan]
 [ nan  nan]
 [ 35.  nan]
 [299.  nan]
 [ 23.  nan]
 [ nan  nan]
 [ 38.  nan]
 [457.  nan]
 [231.  nan]
 [ 60.  nan]
 [ nan  nan]
 [  0.  nan]
 [ 60.  nan]
 [ 53.  nan]
 [  1.  nan]
 [111.  nan]
 [ nan  nan]
 [971.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [666.  nan]
 [  3.  nan]
 [ 16.  nan]
 [ nan  nan]
 [292.  nan]
 [ nan  nan]
 [ nan  nan]
 [183.  nan]
 [ 83.  nan]
 [ nan  nan]
 [299.  nan]
 [  3.  nan]
 [ nan  nan]
 [983.  nan]
 [ nan  nan]
 [ 29.  nan]
 [175.  nan]
 [ nan  nan]
 [ 33.  nan]
 [ 14.  nan]
 [ nan  nan]
 [ 84.  nan]
 [ 16.  nan]
 [ nan  nan]
 [115.  nan]
 [397.  nan]
 [124.  nan]
 [ nan  nan]
 [ nan  nan]
 [  9.  nan]
 [ 13.  nan]
 [ 74.  nan]
 [ 39.  nan]
 [ 55.  nan]
 [ 25.  nan]
 [ nan  nan]
 [ 24.  nan]
 [ nan  nan]
 [662.  nan]
 [ nan  nan]
 [ 16.  nan]
 [  0.  nan]
 [729.  nan]
 [  8.  nan]
 [  6.  nan]
 [  4.  nan]
 [115.  nan]
 [  2.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ 16.  nan]
 [  9.  nan]
 [ 33.  nan]
 [  1.  nan]
 [  1.  nan]
 [ nan  nan]
 [ nan  nan]
 [ 11.  nan]
 [ 13.  nan]
 [ 11.  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [  0.  nan]
 [ 19.  nan]
 [  1.  nan]
 [  0.  nan]
 [  0.  nan]
 [  0.  nan]
 [  0.  nan]
 [  5.  nan]]

In [348]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:5])
x[:, 1:5] = imputer.transform(x[:, 1:5])

In [349]:
x

array([['USA', 252.0, 253.2608695652174, 275.7142857142857],
       ['India', 252.0, 253.2608695652174, 275.7142857142857],
       ['France', 252.0, 253.2608695652174, 275.7142857142857],
       ['Germany', 252.0, 253.2608695652174, 275.7142857142857],
       ['Brazil', 252.0, 253.2608695652174, 275.7142857142857],
       ['Japan', 252.0, 253.2608695652174, 275.7142857142857],
       ['S. Korea', 252.0, 253.2608695652174, 275.7142857142857],
       ['Italy', 252.0, 253.2608695652174, 275.7142857142857],
       ['UK', 252.0, 253.2608695652174, 275.7142857142857],
       ['Russia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Turkey', 252.0, 253.2608695652174, 275.7142857142857],
       ['Spain', 252.0, 253.2608695652174, 275.7142857142857],
       ['Vietnam', 252.0, 253.2608695652174, 275.7142857142857],
       ['Australia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Argentina', 252.0, 253.2608695652174, 275.7142857142857],
       ['Taiwan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Netherlands', 252.0, 253.2608695652174, 275.7142857142857],
       ['Iran', 252.0, 253.2608695652174, 275.7142857142857],
       ['Mexico', 252.0, 253.2608695652174, 275.7142857142857],
       ['Indonesia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Poland', 252.0, 253.2608695652174, 275.7142857142857],
       ['Colombia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Austria', 252.0, 253.2608695652174, 275.7142857142857],
       ['Greece', 252.0, 253.2608695652174, 275.7142857142857],
       ['Portugal', 252.0, 253.2608695652174, 275.7142857142857],
       ['Ukraine', 252.0, 253.2608695652174, 275.7142857142857],
       ['Chile', 252.0, 253.2608695652174, 275.7142857142857],
       ['Malaysia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Israel', 252.0, 253.2608695652174, 275.7142857142857],
       ['DPRK', 252.0, 74.0, 275.7142857142857],
       ['Thailand', 252.0, 253.2608695652174, 275.7142857142857],
       ['Belgium', 252.0, 253.2608695652174, 275.7142857142857],
       ['Czechia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Canada', 252.0, 253.2608695652174, 275.7142857142857],
       ['Peru', 252.0, 253.2608695652174, 275.7142857142857],
       ['Switzerland', 252.0, 253.2608695652174, 275.7142857142857],
       ['Philippines', 252.0, 253.2608695652174, 275.7142857142857],
       ['South Africa', 252.0, 253.2608695652174, 275.7142857142857],
       ['Romania', 252.0, 253.2608695652174, 275.7142857142857],
       ['Denmark', 252.0, 253.2608695652174, 275.7142857142857],
       ['Hong Kong', 252.0, 253.2608695652174, 275.7142857142857],
       ['Sweden', 252.0, 253.2608695652174, 275.7142857142857],
       ['Serbia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Iraq', 252.0, 253.2608695652174, 275.7142857142857],
       ['Singapore', 252.0, 253.2608695652174, 275.7142857142857],
       ['Hungary', 252.0, 253.2608695652174, 275.7142857142857],
       ['New Zealand', 252.0, 253.2608695652174, 275.7142857142857],
       ['Bangladesh', 252.0, 253.2608695652174, 275.7142857142857],
       ['Slovakia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Georgia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Jordan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Ireland', 252.0, 253.2608695652174, 275.7142857142857],
       ['Pakistan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Norway', 252.0, 253.2608695652174, 275.7142857142857],
       ['Finland', 252.0, 253.2608695652174, 275.7142857142857],
       ['Kazakhstan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Slovenia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Lithuania', 252.0, 253.2608695652174, 275.7142857142857],
       ['Bulgaria', 252.0, 253.2608695652174, 275.7142857142857],
       ['Morocco', 252.0, 253.2608695652174, 275.7142857142857],
       ['Croatia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Lebanon', 252.0, 253.2608695652174, 275.7142857142857],
       ['Guatemala', 252.0, 253.2608695652174, 275.7142857142857],
       ['Bolivia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Costa Rica', 252.0, 253.2608695652174, 275.7142857142857],
       ['Tunisia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Cuba', 252.0, 253.2608695652174, 275.7142857142857],
       ['Ecuador', 252.0, 253.2608695652174, 275.7142857142857],
       ['UAE', 252.0, 253.2608695652174, 275.7142857142857],
       ['Uruguay', 252.0, 253.2608695652174, 275.7142857142857],
       ['Panama', 252.0, 253.2608695652174, 275.7142857142857],
       ['Mongolia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Nepal', 252.0, 253.2608695652174, 275.7142857142857],
       ['Belarus', 252.0, 253.2608695652174, 275.7142857142857],
       ['Latvia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Saudi Arabia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Azerbaijan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Paraguay', 252.0, 253.2608695652174, 275.7142857142857],
       ['Bahrain', 252.0, 253.2608695652174, 275.7142857142857],
       ['Sri Lanka', 252.0, 253.2608695652174, 275.7142857142857],
       ['Kuwait', 252.0, 253.2608695652174, 275.7142857142857],
       ['Dominican Republic', 252.0, 253.2608695652174,
        275.7142857142857],
       ['Cyprus', 252.0, 253.2608695652174, 275.7142857142857],
       ['Myanmar', 252.0, 253.2608695652174, 275.7142857142857],
       ['Palestine', 252.0, 253.2608695652174, 275.7142857142857],
       ['Estonia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Moldova', 252.0, 253.2608695652174, 275.7142857142857],
       ['Venezuela', 252.0, 253.2608695652174, 275.7142857142857],
       ['Egypt', 252.0, 253.2608695652174, 275.7142857142857],
       ['Libya', 252.0, 253.2608695652174, 275.7142857142857],
       ['China', 252.0, 253.2608695652174, 275.7142857142857],
       ['Ethiopia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Qatar', 252.0, 686.0, 275.7142857142857],
       ['Réunion', 252.0, 919.0, 275.7142857142857],
       ['Honduras', 252.0, 253.2608695652174, 275.7142857142857],
       ['Armenia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Bosnia and Herzegovina', 252.0, 253.2608695652174,
        275.7142857142857],
       ['Oman', 252.0, 253.2608695652174, 275.7142857142857],
       ['North Macedonia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Kenya', 252.0, 253.2608695652174, 275.7142857142857],
       ['Zambia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Albania', 252.0, 253.2608695652174, 275.7142857142857],
       ['Botswana', 252.0, 253.2608695652174, 275.7142857142857],
       ['Luxembourg', 252.0, 253.2608695652174, 275.7142857142857],
       ['Montenegro', 252.0, 253.2608695652174, 275.7142857142857],
       ['Brunei', 252.0, 225.0, 275.7142857142857],
       ['Algeria', 252.0, 253.2608695652174, 275.7142857142857],
       ['Nigeria', 252.0, 253.2608695652174, 275.7142857142857],
       ['Zimbabwe', 252.0, 253.2608695652174, 275.7142857142857],
       ['Uzbekistan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Mozambique', 252.0, 253.2608695652174, 275.7142857142857],
       ['Martinique', 252.0, 253.2608695652174, 275.7142857142857],
       ['Laos', 252.0, 758.0, 275.7142857142857],
       ['Iceland', 252.0, 229.0, 275.7142857142857],
       ['Afghanistan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Kyrgyzstan', 252.0, 253.2608695652174, 275.7142857142857],
       ['El Salvador', 252.0, 253.2608695652174, 275.7142857142857],
       ['Guadeloupe', 252.0, 253.2608695652174, 275.7142857142857],
       ['Trinidad and Tobago', 252.0, 253.2608695652174,
        275.7142857142857],
       ['Maldives', 252.0, 311.0, 275.7142857142857],
       ['Ghana', 252.0, 253.2608695652174, 275.7142857142857],
       ['Namibia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Uganda', 252.0, 253.2608695652174, 275.7142857142857],
       ['Jamaica', 252.0, 253.2608695652174, 275.7142857142857],
       ['Cambodia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Rwanda', 252.0, 253.2608695652174, 275.7142857142857],
       ['Cameroon', 252.0, 253.2608695652174, 275.7142857142857],
       ['Malta', 252.0, 824.0, 275.7142857142857],
       ['Barbados', 252.0, 571.0, 275.7142857142857],
       ['Angola', 252.0, 253.2608695652174, 275.7142857142857],
       ['Channel Islands', 252.0, 223.0, 275.7142857142857],
       ['French Guiana', 252.0, 420.0, 275.7142857142857],
       ['DRC', 252.0, 253.2608695652174, 275.7142857142857],
       ['Senegal', 252.0, 253.2608695652174, 275.7142857142857],
       ['Malawi', 252.0, 253.2608695652174, 275.7142857142857],
       ['Ivory Coast', 252.0, 833.0, 275.7142857142857],
       ['Suriname', 252.0, 253.2608695652174, 275.7142857142857],
       ['New Caledonia', 252.0, 314.0, 275.7142857142857],
       ['French Polynesia', 252.0, 649.0, 275.7142857142857],
       ['Eswatini', 252.0, 253.2608695652174, 275.7142857142857],
       ['Guyana', 252.0, 253.2608695652174, 275.7142857142857],
       ['Belize', 252.0, 688.0, 275.7142857142857],
       ['Fiji', 252.0, 883.0, 275.7142857142857],
       ['Madagascar', 252.0, 253.2608695652174, 275.7142857142857],
       ['Sudan', 252.0, 253.2608695652174, 275.7142857142857],
       ['Mauritania', 252.0, 997.0, 275.7142857142857],
       ['Cabo Verde', 252.0, 413.0, 275.7142857142857],
       ['Bhutan', 252.0, 21.0, 275.7142857142857],
       ['Syria', 252.0, 253.2608695652174, 275.7142857142857],
       ['Burundi', 252.0, 38.0, 275.7142857142857],
       ['Seychelles', 252.0, 172.0, 275.7142857142857],
       ['Gabon', 252.0, 306.0, 275.7142857142857],
       ['Andorra', 252.0, 165.0, 275.7142857142857],
       ['Papua New Guinea', 252.0, 670.0, 275.7142857142857],
       ['Curaçao', 252.0, 295.0, 275.7142857142857],
       ['Aruba', 252.0, 236.0, 275.7142857142857],
       ['Tanzania', 252.0, 846.0, 275.7142857142857],
       ['Mayotte', 252.0, 188.0, 275.7142857142857],
       ['Mauritius', 252.0, 253.2608695652174, 275.7142857142857],
       ['Togo', 252.0, 290.0, 275.7142857142857],
       ['Guinea', 252.0, 467.0, 275.7142857142857],
       ['Isle of Man', 252.0, 116.0, 275.7142857142857],
       ['Bahamas', 252.0, 833.0, 275.7142857142857],
       ['Lesotho', 252.0, 723.0, 275.7142857142857],
       ['Faeroe Islands', 252.0, 28.0, 275.7142857142857],
       ['Haiti', 252.0, 860.0, 275.7142857142857],
       ['Mali', 252.0, 743.0, 275.7142857142857],
       ['Cayman Islands', 252.0, 37.0, 275.7142857142857],
       ['Saint Lucia', 252.0, 409.0, 275.7142857142857],
       ['Benin', 252.0, 163.0, 275.7142857142857],
       ['Somalia', 252.0, 253.2608695652174, 275.7142857142857],
       ['Congo', 252.0, 386.0, 275.7142857142857],
       ['Solomon Islands', 252.0, 153.0, 275.7142857142857],
       ['San Marino', 252.0, 122.0, 275.7142857142857],
       ['Timor-Leste', 252.0, 138.0, 275.7142857142857],
       ['Micronesia', 252.0, 58.0, 275.7142857142857],
       ['Burkina Faso', 252.0, 396.0, 275.7142857142857],
       ['Liechtenstein', 252.0, 89.0, 275.7142857142857],
       ['Gibraltar', 252.0, 111.0, 275.7142857142857],
       ['Grenada', 252.0, 238.0, 275.7142857142857],
       ['Bermuda', 252.0, 157.0, 275.7142857142857],
       ['Nicaragua', 252.0, 225.0, 275.7142857142857],
       ['South Sudan', 252.0, 138.0, 275.7142857142857],
       ['Tajikistan', 252.0, 125.0, 275.7142857142857],
       ['Equatorial Guinea', 252.0, 183.0, 275.7142857142857],
       ['Tonga', 252.0, 13.0, 275.7142857142857],
       ['Samoa', 252.0, 29.0, 275.7142857142857],
       ['Monaco', 252.0, 65.0, 275.7142857142857],
       ['Dominica', 252.0, 74.0, 275.7142857142857],
       ['Djibouti', 252.0, 189.0, 275.7142857142857],
       ['Marshall Islands', 252.0, 17.0, 275.7142857142857],
       ['CAR', 252.0, 113.0, 275.7142857142857],
       ['Gambia', 252.0, 372.0, 275.7142857142857],
       ['Saint Martin', 252.0, 63.0, 275.7142857142857],
       ['Vanuatu', 252.0, 14.0, 275.7142857142857],
       ['Greenland', 252.0, 21.0, 275.7142857142857],
       ['Yemen', 252.0, 253.2608695652174, 275.7142857142857],
       ['Caribbean Netherlands', 252.0, 38.0, 275.7142857142857],
       ['Sint Maarten', 252.0, 89.0, 275.7142857142857],
       ['Eritrea', 252.0, 103.0, 275.7142857142857],
       ['Niger', 252.0, 312.0, 275.7142857142857],
       ['St. Vincent Grenadines', 252.0, 123.0, 275.7142857142857],
       ['Antigua and Barbuda', 252.0, 146.0, 275.7142857142857],
       ['Comoros', 252.0, 161.0, 275.7142857142857],
       ['Guinea-Bissau', 252.0, 176.0, 275.7142857142857],
       ['Liberia', 252.0, 294.0, 275.7142857142857],
       ['Sierra Leone', 252.0, 126.0, 275.7142857142857],
       ['Chad', 252.0, 194.0, 275.7142857142857],
       ['British Virgin Islands', 252.0, 64.0, 275.7142857142857],
       ['Cook Islands', 252.0, 2.0, 275.7142857142857],
       ['Saint Kitts and Nevis', 252.0, 46.0, 275.7142857142857],
       ['Turks and Caicos', 252.0, 38.0, 275.7142857142857],
       ['Sao Tome and Principe', 252.0, 77.0, 275.7142857142857],
       ['Palau', 252.0, 9.0, 275.7142857142857],
       ['St. Barth', 252.0, 6.0, 275.7142857142857],
       ['Kiribati', 252.0, 18.0, 275.7142857142857],
       ['Nauru', 252.0, 1.0, 275.7142857142857],
       ['Anguilla', 252.0, 12.0, 275.7142857142857],
       ['Macao', 252.0, 120.0, 275.7142857142857],
       ['Saint Pierre Miquelon', 252.0, 2.0, 275.7142857142857],
       ['Wallis and Futuna', 252.0, 7.0, 438.0],
       ['Tuvalu', 252.0, 253.2608695652174, 275.7142857142857],
       ['Saint Helena', 252.0, 253.2608695652174, 2.0],
       ['Falkland Islands', 252.0, 253.2608695652174, 275.7142857142857],
       ['Montserrat', 252.0, 8.0, 275.7142857142857],
       ['Niue', 747.0, 253.2608695652174, 746.0],
       ['Diamond Princess', 712.0, 13.0, 699.0],
       ['Vatican City', 29.0, 253.2608695652174, 29.0],
       ['Western Sahara', 10.0, 1.0, 9.0],
       ['MS Zaandam', 9.0, 2.0, 7.0],
       ['Tokelau', 5.0, 253.2608695652174, 275.7142857142857]],
      dtype=object)

In [350]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(y[:, -3:])
y[:, -3:] = imputer.transform(y[:, -3:])

In [351]:
y

array([[179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [  0.     ,   0.     ],
       [483.     , 483.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [673.     , 673.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [638.     , 638.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [909.     , 909.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [ 63.     ,  63.     ],
       [535.     , 535.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [109.     , 109.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [899.     , 899.     ],
       [ 34.     ,  34.     ],
       [ 18.     ,  18.     ],
       [179.87254, 179.87254],
       [307.     , 307.     ],
       [179.87254, 179.87254],
       [205.     , 205.     ],
       [179.87254, 179.87254],
       [509.     , 509.     ],
       [  3.     ,   3.     ],
       [ 51.     ,  51.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [ 31.     ,  31.     ],
       [159.     , 159.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [739.     , 739.     ],
       [179.87254, 179.87254],
       [  4.     ,   4.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [263.     , 263.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [167.     , 167.     ],
       [ 82.     ,  82.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [493.     , 493.     ],
       [179.87254, 179.87254],
       [348.     , 348.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [956.     , 956.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [318.     , 318.     ],
       [179.87254, 179.87254],
       [ 14.     ,  14.     ],
       [201.     , 201.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [ 13.     ,  13.     ],
       [ 63.     ,  63.     ],
       [179.87254, 179.87254],
       [615.     , 615.     ],
       [ 16.     ,  16.     ],
       [ 37.     ,  37.     ],
       [115.     , 115.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [  2.     ,   2.     ],
       [504.     , 504.     ],
       [ 11.     ,  11.     ],
       [179.87254, 179.87254],
       [  5.     ,   5.     ],
       [179.87254, 179.87254],
       [ 35.     ,  35.     ],
       [299.     , 299.     ],
       [ 23.     ,  23.     ],
       [179.87254, 179.87254],
       [ 38.     ,  38.     ],
       [457.     , 457.     ],
       [231.     , 231.     ],
       [ 60.     ,  60.     ],
       [179.87254, 179.87254],
       [  0.     ,   0.     ],
       [ 60.     ,  60.     ],
       [ 53.     ,  53.     ],
       [  1.     ,   1.     ],
       [111.     , 111.     ],
       [179.87254, 179.87254],
       [971.     , 971.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [666.     , 666.     ],
       [  3.     ,   3.     ],
       [ 16.     ,  16.     ],
       [179.87254, 179.87254],
       [292.     , 292.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [183.     , 183.     ],
       [ 83.     ,  83.     ],
       [179.87254, 179.87254],
       [299.     , 299.     ],
       [  3.     ,   3.     ],
       [179.87254, 179.87254],
       [983.     , 983.     ],
       [179.87254, 179.87254],
       [ 29.     ,  29.     ],
       [175.     , 175.     ],
       [179.87254, 179.87254],
       [ 33.     ,  33.     ],
       [ 14.     ,  14.     ],
       [179.87254, 179.87254],
       [ 84.     ,  84.     ],
       [ 16.     ,  16.     ],
       [179.87254, 179.87254],
       [115.     , 115.     ],
       [397.     , 397.     ],
       [124.     , 124.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [  9.     ,   9.     ],
       [ 13.     ,  13.     ],
       [ 74.     ,  74.     ],
       [ 39.     ,  39.     ],
       [ 55.     ,  55.     ],
       [ 25.     ,  25.     ],
       [179.87254, 179.87254],
       [ 24.     ,  24.     ],
       [179.87254, 179.87254],
       [662.     , 662.     ],
       [179.87254, 179.87254],
       [ 16.     ,  16.     ],
       [  0.     ,   0.     ],
       [729.     , 729.     ],
       [  8.     ,   8.     ],
       [  6.     ,   6.     ],
       [  4.     ,   4.     ],
       [115.     , 115.     ],
       [  2.     ,   2.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [ 16.     ,  16.     ],
       [  9.     ,   9.     ],
       [ 33.     ,  33.     ],
       [  1.     ,   1.     ],
       [  1.     ,   1.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [ 11.     ,  11.     ],
       [ 13.     ,  13.     ],
       [ 11.     ,  11.     ],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [179.87254, 179.87254],
       [  0.     ,   0.     ],
       [ 19.     ,  19.     ],
       [  1.     ,   1.     ],
       [  0.     ,   0.     ],
       [  0.     ,   0.     ],
       [  0.     ,   0.     ],
       [  0.     ,   0.     ],
       [  5.     ,   5.     ]], dtype=float32)

In [352]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
x = np.array(ct.fit_transform(x).toarray())

In [353]:
x

array([[  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       [  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       [  0.        ,   0.        ,   0.        , ..., 252.        ,
        253.26086957, 275.71428571],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  10.        ,
          1.        ,   9.        ],
       [  0.        ,   0.        ,   0.        , ...,   9.        ,
          2.        ,   7.        ],
       [  0.        ,   0.        ,   0.        , ...,   5.        ,
        253.26086957, 275.71428571]])

In [354]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
z = le.fit_transform(z)

In [355]:
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)